services:
  - type: web
    name: ribbon-calculator
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://craftprofitoptimizer_user:b8r0V9NvfvYsyBuekNmKCLjQJwsFWAGm@dpg-d22gsae3jp1c738tmkrg-a.oregon-postgres.render.com/craftprofitoptimizer
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://ribbon-calculator.onrender.com
      - key: NEXT_PUBLIC_APP_URL
        value: https://ribbon-calculator.onrender.com
    healthCheckPath: /
    autoDeploy: true 